[package]
name = "alacritty_terminal"
version = "0.16.1-dev"
authors = ["Christian Duerr <contact@christianduerr.com>", "Joe Wilm <joe@jwilm.com>"]
license = "Apache-2.0"
description = "Library for writing terminal emulators"
readme = "../README.md"
homepage = "https://github.com/alacritty/alacritty"
edition = "2021"
rust-version = "1.56.0"

[dependencies.alacritty_config_derive]
path = "../alacritty_config_derive"
version = "0.1.0"

[dependencies]
libc = "0.2"
bitflags = "1"
parking_lot = "0.11.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
vte = { version = "0.10.0", default-features = false }
mio = "0.6.20"
mio-extras = "2"
log = "0.4"
unicode-width = "0.1"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.5"
hyper = "0.13.6"
hyper-tls = "0.4.1"
serde_derive = "1.0"
serde_json = "1"
env_logger = "0.7"
tracing = { version = "0.1", features = ["log", "log-always"] }
tracing-log = { version = "0.1", features = ["env_logger"]}
percent-encoding = "1.0.1"
failure = "0.1.6"
rand = "0.7.3"
base64 = "0.13.0"
regex-automata = "0.1.9"
dirs = "3.0.1"

[target.'cfg(unix)'.dependencies]
nix = "0.22.0"
signal-hook = "0.3.10"
signal-hook-mio = { version = "0.2.1", features = ["support-v0_6"] }

[target.'cfg(windows)'.dependencies]
miow = "0.3"
winapi = { version = "0.3.7", features = [
    "impl-default", "basetsd", "libloaderapi", "minwindef", "ntdef", "processthreadsapi", "winbase",
    "wincon", "wincontypes", "winerror", "winnt", "winuser", "consoleapi",
]}
mio-anonymous-pipes = "0.2"

[dev-dependencies]
serde_json = "1.0.0"
